name: Update Language Stats GIF

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  language-stats:
    runs-on: ubuntu-latest

    permissions: 
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas pillow requests

      - name: Verify GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ -z "${GH_TOKEN}" ]]; then
            echo " GitHub token (GH_TOKEN) is missing. Ensure it's set in repository secrets."
            exit 1
          else
            echo " GitHub token is available."
          fi

      - name: Generate Language Stats GIF
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python generate_language_stats.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add language_stats.gif
          if git status | grep -q 'language_stats.gif'; then
            git commit -m " Update language stats GIF"
            git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo " No changes to commit."
          fi
